### ISSUE TITLE
TODO developers docs

### ISSUE THREAD

**Issue by jesserockz** [esphome/developers.esphome.io#2]
## Overview/High-level
- [x] Basic introduction/home page
- [x] Introduction to hardware interfaces (I2C, SPI, UART, GPIOs) #32 
- [x] Various commonly-used consts/variables (`CONF_*`, `AUTO_LOAD`, `to_code`, etc.)
- [x] Logo #38 
- [x] Favicon #38

## Code
- [x] Basic component CONSTs (`AUTO_LOAD`, `DEPENDENCIES`, `CODEOWNERS`, `MULTI_CONF`, `MULTI_CONF_NO_DEFAULT`)
- [x] Always use the api generation script if you modify api.proto #8 
- [x] use walrus operator for optional config gathering  - `sensor_config := config.get(CONF_SENSOR)` - except for boolean values. #8 
- [x] No AUTO_LOADing the main platform components (sensor, binary_sensor etc) #8
- [x] Any literal string used more than once should be defined as a constant. #8
- [x] Configuration keys (i.e. those that appear as keys in YAML) should be defined (even if only used once) as constants of the form `CONF_XXX` where `XXX` is the upper-case version of the YAML key. #8 
- [x] Configuration constants used only in a single component should be defined within that component. If the same constant is used in 2 or more components it *may* be migrated to `esphome/const.py`. If it appears in 4 or more components it **must** be migrated to `esphome/const.py` (will fail CI checks otherwise.) #8
- [x] Coroutine priorities (see https://github.com/esphome/esphome/pull/6755)

## Tests

- [x] All components should have test yaml files located in `tests/components/<component name>/test.<platform>.yaml` and this yaml should contain every configuration option being set and any actions and conditions the component has.

## Documentation
- [x] Documentation example is to be minimum required to compile, optional configs not to be included. Pin values should always be the string `REPLACEME` #8 
- [x] Example should not include dependent components, but a sentence and link to the relevant configuration documentation #8 
- [x] If a component is used exclusively, or primarily, on a single specific board (i.e. with dedicated pin numbers) a complete configuration for the component on that board *may* be included as a sample at the end of the doc, clearly identified as being for that hardware. This should not replace the generic example configuration. #8 
- [x] How to do actions/conditions (and triggers?) (related to the item below) #38 

## Traps for the unwary
- [ ] If you just added a new validation function and your code blows up, check that the validation function has `return value` at the end.

**Comment by clydebarrow** [comment]
[ ] If a component is used exclusively, or primarily, on a single specific board (i.e. with dedicated pin numbers) a complete configuration for the component on that board *may* be included as a sample at the end of the doc, clearly identified as being for that hardware. This should not replace the generic example configuration.

**Comment by clydebarrow** [comment]
- [ ] Configuration constants (`CONF_xxxx`) used only in a single component should be defined within that component. If the same constant is used in 2 or more components it *may* be migrated to `esphome/core/const.py`. If it appears in 4 or more components it **must** be migrated to `esphome/core/const.py` (will fail CI checks otherwise.)

**Comment by kbx81** [comment]
Which tests are required is not determined (directly) by what SoCs are "recommended". See https://developers.esphome.io/architecture/overview/#test-configurations

**Comment by ximex** [comment]
but shouldn't we document somewhere that Python 3.10 is the min required version? see: https://github.com/esphome/esphome/pull/8850

**Comment by jesserockz** [comment]
> > but shouldn't we document somewhere that Python 3.10 is the min required version? see: [esphome/esphome#8850](https://github.com/esphome/esphome/pull/8850)
> 
> [@ximex](https://github.com/ximex) it's there -- see [developers.esphome.io/contributing/development-environment#requirements](https://developers.esphome.io/contributing/development-environment/#requirements)

@kbx81 That says 3.12 is the min which is not exactly true. The current min is 3.10
